project:
  type: website
  render:
    - "*.qmd"
    - "!cv.qmd"
    - "!resume-old.qmd"
  resources:
    - robots.txt
    - llms.txt

bibliography: assets/my-publication-list.bib

website:
  site-url: "https://lszabo.me"
  # google-analytics: "G-B84ES4BRHJ"
  title: "Laszlo Szabo"
  description: "Academic portfolio of Laszlo Szabo, Consultant Transplant Surgeon at Cardiff Transplant Unit. Research in kidney and pancreas transplantation, organ utilisation, and data science."
  favicon: images/favicon.svg

  open-graph: true
  twitter-card:
    site: "@drszabolaszlo"
  
  navbar:
    left:
      - text: CV
        href: resume.qmd
      - text: Research
        href: publications.qmd
      - text: Posts
        href: posts.qmd
    
    right:
      
      - icon: github
        href: https://github.com/Laszlo75
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-6881-1542
      - icon: linkedin
        href: https://www.linkedin.com/in/drszabolaszlo/
      - icon: twitter
        href: https://twitter.com/drszabolaszlo
      - icon: envelope
        aria-label: email
        href: "mailto:laszlo.szabo@wales.nhs.uk"

  page-footer:
    left: "&copy; 2026 Laszlo Szabo"

    center: <span class="faux-block">{{< fa brands orcid >}} [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>

    right:
      - icon: github
        text: "Source"
        href: https://github.com/Laszlo75
       
      
   # background: "#2780e3"

format:
  html:
    theme: flatly
    css: styles.css
    include-after-body: assets/cloudflare-analytics.html

editor: source

